# Generated by Django 3.2.13 on 2022-05-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countryGDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(max_length=60)),
                ('year', models.CharField(max_length=60)),
                ('gdp', models.CharField(max_length=60)),
            ],
        ),
    ]
