# Generated by Django 3.2.13 on 2022-05-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpapi', '0002_gdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdp',
            name='China',
            field=models.IntegerField(default=40, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gdp',
            name='Europe',
            field=models.IntegerField(default=22, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gdp',
            name='India',
            field=models.IntegerField(default=45, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gdp',
            name='USA',
            field=models.IntegerField(default=60, max_length=4),
            preserve_default=False,
        ),
    ]
